Numpy array

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
a = [1.1,2,3,"4"]
a
type(a)

list

In [ ]:
print(a)

[1.1, 2, 3, '4']


In [ ]:
arr1 = np.array(a)
arr1

array(['1.1', '2', '3', '4'], dtype='<U32')

In [ ]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr2 = np.array(l)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generating function

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = np.zeros(9)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.zeros((2,6))
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
o = np.ones((5,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
l = np.linspace(0,10,20)
l

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Random Generation function

In [ ]:
np.random.rand(10)

array([0.95344264, 0.65790648, 0.56174939, 0.25316044, 0.08928772,
       0.35073179, 0.52646603, 0.50039268, 0.20169294, 0.72542988])

In [ ]:
np.random.randn(10)

array([ 0.17657509, -0.25716625, -1.75714384, -2.31788174,  1.55644806,
        0.34332584,  0.2590077 ,  1.03631218,  0.7752707 , -1.18484084])

In [ ]:
np.random.randint(10,20,10)

array([15, 19, 13, 16, 19, 14, 11, 10, 17, 19])

Array Attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

Array Methods


In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

Reshaping and resizing

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = np.reshape(arr, (5,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

Numpy Indexing and Silicong of Vectors


In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[9]

np.int64(20)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr[2::3]

array([13, 16, 19])

Matrix Silicing and Indexing


In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[0][1]

np.int64(2)

In [ ]:
arr[2:, 4:]

array([[17, 18],
       [23, 24],
       [29, 30]])

Bool Index


In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])

Shallow and Deep copy


In [ ]:
a = np.arange(1,11)
b = np.arange(11,21)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
c = a + b
d = a - b
print(c)
print(d)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]


In [ ]:
f = a
f += 1
print(f)

[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
e = a.copy()
e += 1
print(e)

[ 3  4  5  6  7  8  9 10 11 12]


In [ ]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Advance array manipulation


Stacking Array

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
np.stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
np.vsplit(c,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

Excercises

Valid Sudoko

In [ ]:
s = np.array([
 [5, 3, 4, 6, 7, 8, 9, 1, 2],
 [6, 7, 2, 1, 9, 5, 3, 4, 8],
 [1, 9, 8, 3, 4, 2, 5, 6, 7],
 [8, 5, 9, 7, 6, 1, 4, 2, 3],
 [4, 2, 6, 8, 5, 3, 7, 9, 1],
 [7, 1, 3, 9, 2, 4, 8, 5, 6],
 [9, 6, 1, 5, 3, 7, 2, 8, 4],
 [2, 8, 7, 4, 1, 9, 6, 3, 5],
 [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b = np.sum(s, axis=1)
for i in b:
  if i != 45:
    print("Sudoko is not valid")
    break
  else:
    print("Sudoko is valid for Rows")
    break

Sudoko is valid for Rows


In [ ]:
c = np.sum(s, axis=0)
if i in c:
  if i != 45:
    print("Sudoko is not valid")
  else:
    print("Sudoko is valid for Columns")

Sudoko is valid for Columns


In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0, 9, 3):
  for j in range(0, 8, 3):
    print(s[i:i+3, j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


General Questions

In [ ]:
# col1 = age, col2 = math marks, col3 = science marks
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18,65, 70],
    [20, 90, 85]
])

In [ ]:
# Data shape
data.shape

(5, 3)

In [ ]:
# age avergae
age_avg = np.mean(data[:,0])
print(age_avg)

18.4


In [ ]:
# math marks columns
math_marks = data[:,1]
print(math_marks)

[85 92 76 65 90]


In [ ]:
# highest science marks
hm = np.max(data[:,2])
print(hm)

95


In [ ]:
# details of std who scored more than 90 in math
std_details = data[data[:,1] > 90]
print(std_details)

[[19 92 88]]


In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# inc math marks 5 in all rows
data[:,1] + 5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# get all std younger than 19
len(data[data[:,0] < 19])

3

In [ ]:
# avg of subjects
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [ ]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])